### ISSUE TITLE
Is Ionide / editor analysers supported?

### ISSUE THREAD

**Issue by MangelMaxime** [G-Research/fsharp-analyzers#41]
Hello,

According to [Ionide documentation](https://ionide.io/FSharp.Analyzers.SDK/) and [announcement blog post](https://medium.com/lambda-factory/introducing-f-analyzers-772487889429), it should be possible to have Analysers reported in VSCode / FSAC based IDE.

I activated the option in Ionide however, there was no analysers warning reported in the editor. Is it something supported by the analysers from this repository?

**Comment by nojaf** [comment]
It is on our radar for sure!

**Comment by nojaf** [comment]
This should work in the latest version of all involved components.

**Comment by MangelMaxime** [comment]
Awesome, I will have a look at it in the future :)
