### ISSUE TITLE
Consider rearranging tests to fit in the IDE

### ISSUE THREAD

**Issue by Smaug123** [G-Research/fsharp-analyzers#60]
If we moved `data` into the `FSharp.Analyzers.Tests` folder, and added the following to the test fsproj, then the test files would show up in the IDE:

```xml
  <ItemGroup>
    <None Include="data\**\*.fs*" />
  </ItemGroup>
```

(One of the infinitely many inconsistencies of MSBuild appears to be that `**` wildcard expansion doesn't work in paths which start with `..\`. Otherwise this change could be done without moving the `data` directory.)

Feel free not to do this; it just seems like a better experience for contributors.

**Comment by nojaf** [comment]
Thanks for this suggestion!

We mirrored this approach from what the Rider team does: https://github.com/JetBrains/resharper-fsharp/tree/main/ReSharper.FSharp/test

But since we only have one test project, we could indeed just move this.
