### ISSUE TITLE
False positive on matching log args

### ISSUE THREAD

**Issue by Smaug123** [G-Research/fsharp-analyzers#69]
I observed today in GR that `GRA-LOGTEMPLMISSVALS-001` incorrectly fired on the following:

```fsharp
log.LogWarning(e, "Error: {Something}", 3)
```

Since the first argument inherits from `Exception`, it should be ignored for the purposes of this analyzer.

**Comment by Smaug123** [comment]
Oh sorry, I'll try and reproduce it internally and get an exact repro out to you.

**Comment by dawedawe** [comment]
Cool, thanks!

**Comment by nojaf** [comment]
@dawedawe sample to reproduce should be:
```
namespace Blah

open Microsoft.Extensions.Logging

module Program =
    [<EntryPoint>]
    let main argv =
        let log : ILogger = failwith "TODO"
        try
            failwith "no"
        with e ->
            log.LogError (e, "Failed to look up: {s_Group}", 3)
            raise e
        0
```
