### ISSUE TITLE
Colons should also be allowed inside log templates

### ISSUE THREAD

**Issue by nojaf** [G-Research/fsharp-analyzers#78]
From the trenches:

```fsharp
logger.LogDebug("Blah {s_thing:l} foo {s_other_thing:l}", someString, someOtherString)
```

See https://github.com/serilog/serilog/wiki/Formatting-Output

Colons are allowed in this case.

Can you check this please @dawedawe?

**Comment by Smaug123** [comment]
There's a chance there's no correct validation possible here and we should just detect grouped braces.
